language: java
sudo: false
jdk:
  - oraclejdk8

branches:
  only:
    - master

services:
  - mysql

before_install:
  - mysql -u travis -e 'CREATE DATABASE dos;'
  - mysql -u travis -e "CREATE USER 'dos'@'localhost' IDENTIFIED BY 'dos';"
  - mysql -u travis -e "GRANT ALL PRIVILEGES ON * . * TO 'dos'@'localhost';"
  

script:
  - mvn test
