language: java
sudo: false
jdk:
  - oraclejdk8

branches:
  only:
    - master

services:
  - mysql

before_install:
  - mysql -e 'CREATE USER IF NOT EXISTS 'dos'@'localhost' IDENTIFIED BY 'dos';'
  - mysql -e 'GRANT ALL PRIVILEGES ON * . * TO 'dos'@'localhost';'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS dos;'

script:
  - mvn test
