language: java
sudo: false
jdk:
  - oraclejdk8

branches:
  only:
    - master

services:
  - mysql

before_install:
  - mysql -u travis -e 'CREATE DATABASE dos;'
  #- mysql -u travis -e "CREATE USER 'travis'@'localhost' IDENTIFIED BY '';"
  #- mysql -u travis -e "GRANT ALL ON dos.* TO 'travis'@'localhost';"
  

script:
  - mvn test
