server:
  port: ${PORT:8080}
  contextPath: ${context.path:/}
  
  
spring:
  datasource:
    # TODO add SSL connection
    url: jdbc:mysql://localhost:3306/dos?useSSL=false
    username: dos
    password: dos
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


keycloak:
  principal-attribute: ekeilty
  auth-server-url: http://localhost:8180/auth
  realm: dos-server
  resource: dos-server-app
  public-client: true


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
