server:
  port: 8101

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${db.database:dos}?useSSL=false
    username: ${db.username:dos}
    password: ${db.password:dos}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

security:
  user:
    name: dosadmin
    password: dosadmin
    role: admin

management:
  context-path: /actuator

keycloak:
  principal-attribute: ekeilty
  auth-server-url: http://localhost:8180/auth
  realm: DNAstack
  resource: dos-server-app
  public-client: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE

---
# This profile is only to remove the MySQL dependency from the "contextLoads" test, which gives early feedback that
# Spring autowiring is likely to work at runtime. Additional Spring integration tests are strongly discouraged because
# they have an unfavourable cost/benefit ratio as compared to more stable e2e tests and faster, simpler Mockito tests.
spring:
  profiles: test

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
