server:
  port: ${PORT:8080}
  contextPath: ${context.path:/}
  
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${db.database:dos}?useSSL=false
    username: ${db.username:dos}
    password: ${db.password:dos}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

security:
  user:
    name: dosadmin
    password: dosadmin
    role: admin

keycloak:
  principal-attribute: ekeilty
  auth-server-url: http://localhost:8180/auth
  realm: DNAstack
  resource: dos-server-app
  public-client: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
